# Generated by Django 5.2.8 on 2025-11-14 18:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicion',
            name='fecha_hora',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
